fhhwr/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from users import views

urlpatterns = [
    path("", views.base_view, name="home"),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("tasks/", include("tasks.urls", namespace="tasks")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"

urlpatterns = [
    path("<int:pk>/update/", views.TaskUpdateView.as_view(), name="task_update"),
    path("<int:pk>/", views.TaskDetailView.as_view(), name="task_detail"),
    path("", views.TaskListView.as_view(), name="task_list"),
    path("<int:pk>/accept/", views.task_accept, name="task_accept"),
    path("<int:pk>/reject/", views.task_reject, name="task_reject"),
    path("<int:pk>/complete/", views.task_complete, name="task_complete"),
    path("<int:pk>/rate/", views.task_rate, name="task_rate"),
    path("create/", views.TaskCreateView.as_view(), name="task_create_button"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("", views.base_view, name="home"),
    path(
        "register/customer/",
        views.CustomerRegistrationView.as_view(),
        name="customer_registration",
    ),
    path(
        "register/worker/",
        views.WorkerRegistrationView.as_view(),
        name="worker_registration",
    ),
    path(
        "update/customer/", views.CustomerUpdateView.as_view(), name="customer_update"
    ),
    path("update/worker/", views.WorkerUpdateView.as_view(), name="worker_update"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path("profile/", views.UserProfileView.as_view(), name="profile"),
    path(
        "activate/<str:uidb64>/<str:token>/",
        views.ActivateAccountView.as_view(),
        name="activate_account",
    ),
    path(
        "activate-worker/<uidb64>/<token>/",
        views.ActivateWorkerView.as_view(),
        name="activate_worker",
    ),
    path(
        "worker-profile/<int:pk>/",
        views.WorkerProfileView.as_view(),
        name="worker_profile",
    ),
]

tasks/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from users.models import Customer, Worker
from django.core.validators import MinValueValidator


class Task(models.Model):
    STATUS_CHOICES = [
        ("requested", _("Requested")),
        ("in-progress", _("In progress")),
        ("completed", _("Completed")),
        ("rejected", _("Rejected")),
        ("vanished", _("Vanished")),
    ]
    request_id = models.CharField(max_length=50, null=True, blank=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    worker = models.ForeignKey(Worker, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=100)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    location = models.CharField(max_length=255)
    created_time = models.DateTimeField(auto_now_add=True)
    last_updated_time = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default="requested"
    )
    rating = models.IntegerField(blank=True, null=True)
    review = models.TextField(blank=True)
    hourly_rate = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        blank=True,
        null=True,
    )
    total_cost = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        blank=True,
        null=True,
    )

    class Meta:
        ordering = ["-created_time"]


class TaskNotification(models.Model):
    task = models.ForeignKey(
        Task, on_delete=models.CASCADE, related_name="notifications"
    )
    message = models.CharField(max_length=255)
    created_time = models.DateTimeField(auto_now_add=True)
    customer = models.ForeignKey(
        Customer, on_delete=models.CASCADE, related_name="task_notifications"
    )

    def __str__(self):
        return self.message

tasks/forms.py
from django import forms
from .models import Task


class TaskCreateForm(forms.ModelForm):
    start_time = forms.DateTimeField(
        input_formats=["%Y-%m-%dT%H:%M"],
        widget=forms.DateTimeInput(
            attrs={"type": "datetime-local", "class": "form-control"},
            format="%Y-%m-%dT%H:%M",
        ),
        required=True,
    )

    end_time = forms.DateTimeField(
        input_formats=["%Y-%m-%dT%H:%M"],
        widget=forms.DateTimeInput(
            attrs={"type": "datetime-local", "class": "form-control"},
            format="%Y-%m-%dT%H:%M",
        ),
        required=True,
    )

    title = forms.CharField(required=True)
    description = forms.CharField(
        required=True, widget=forms.Textarea(attrs={"rows": 5})
    )
    location = forms.CharField(required=True)

    class Meta:
        model = Task
        fields = [
            "title",
            "description",
            "start_time",
            "end_time",
            "location",
        ]
        widgets = {
            "title": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "eg - cleaning"}
            ),
            "description": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "rows": 5,
                    "placeholder": "eg - cleaning my flat having 4 rooms",
                }
            ),
            "location": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "eg - kathmandu"}
            ),
        }


class TaskStatusUpdateForm(forms.ModelForm):
    STATUS_CHOICES = [
        ("requested", "Requested"),
        ("in-progress", "In Progress"),
        ("completed", "Completed"),
        ("rejected", "Rejected"),
    ]

    status = forms.ChoiceField(choices=STATUS_CHOICES, required=True)

    class Meta:
        model = Task
        fields = ["status"]
        labels = {"status": "Status"}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Get the current status of the task
        current_status = self.instance.status
        # Define the valid status transitions
        valid_transitions = {
            "requested": ["in-progress", "rejected"],
            "in-progress": ["completed"],
        }
        # Update the choices for the status field based on the current status
        self.fields["status"].choices = [
            (choice, label)
            for choice, label in self.fields["status"].choices
            if choice in valid_transitions[current_status]
        ]

tasks/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic import CreateView, UpdateView, DetailView, ListView
from django.contrib.auth.models import Group
from .models import Task, TaskNotification
from .forms import TaskCreateForm, TaskStatusUpdateForm
from users.models import Worker
from django.utils.decorators import method_decorator
from django.core import serializers
from decimal import Decimal
from django.db.models import Q, Count, Avg
from django.utils import timezone
import uuid
from tasks.recommendations import pearson_correlation_coefficient


class TaskCreateView(CreateView):
    """
    View for creating a new task. Inherits from Django's CreateView class.
    Allows a customer to create a new task by providing the task details.
    Uses the TaskCreateForm form to get the details of the task.
    On successful submission of the form, assigns the task to a worker based on their skills,
    ratings, and availability using a custom algorithm.
    Sends a request to the top 5 matching workers based on their skills and ratings.
    If no matching workers are found, uses the Pearson correlation coefficient to find
    similar workers and sends the request to them.
    """

    model = Task
    form_class = TaskCreateForm
    template_name = "tasks/task_create.html"
    success_url = reverse_lazy("tasks:task_list")

    def form_valid(self, form):
        """
        If the form is valid, creates a new task instance with the provided form data.
        Finds a matching worker based on their skills, ratings, and availability using a custom algorithm.
        Sends a task request to the top 5 matching workers.
        """
        # Set the customer for the task
        form.instance.customer = self.request.user.customer

        # Get the start and end times for the task
        start_time = form.cleaned_data.get("start_time")
        end_time = form.cleaned_data.get("end_time")

        # Get the available workers for the given time range
        available_workers = Worker.objects.filter(is_available=True)

        # Check for conflicting tasks with in-progress status
        conflicting_tasks = Task.objects.filter(
            worker__in=available_workers,
            status="in-progress",
            start_time__lt=end_time,
            end_time__gt=start_time,
        ).distinct()

        # Exclude the workers with conflicting tasks
        available_workers = available_workers.exclude(
            id__in=[task.worker.id for task in conflicting_tasks]
        )

        # Get the related workers based on their skills and ratings
        query = form.cleaned_data.get("title")
        matching_workers = available_workers.filter(skills__icontains=query)

        # Initialize top_worker to None as a fallback
        top_worker = None

        if matching_workers.exists():
            # Get the top 5 related workers based on their ratings and completed tasks
            related_workers = (
                matching_workers.annotate(
                    rating=Avg("task__rating"),
                    tasks_completed=Count("task", filter=Q(task__status="completed")),
                )
                .order_by("-tasks_completed", "-rating")
                .filter(skills__icontains=query)[:5]
            )

        else:
            # If no worker with matching skills, use Pearson correlation coefficient
            print("No related workers found, so using Pearson coefficient")
            # If no worker with matching skills, use the first available worker as fallback
            top_worker = (
                available_workers.annotate(
                    rating=Avg("task__rating"),
                    tasks_completed=Count("task", filter=Q(task__status="completed")),
                )
                .order_by("-tasks_completed", "-rating")
                .first()
            )
            print(top_worker)
            # Call the function to generate task recommendations using Pearson correlation coefficient
            related_workers = pearson_correlation_coefficient(
                top_worker.id, available_workers, n=5
            )

        # Generate a new request ID
        request_id = str(uuid.uuid4())

        # Send the task request to the related workers
        top_five_workers = []
        related_workers_count = 0
        for worker in related_workers:
            task = form.save(commit=False)
            task.pk = None  # Create a new task instance
            task.worker = worker
            task.request_id = request_id  # Set the request ID
            task.hourly_rate = worker.hourly_rate
            task.save()
            top_five_workers.append(worker.user.username)
            related_workers_count += 1

        # Print the list of related workers who have been sent the task request
        if related_workers_count > 0:
            print(
                f"{related_workers_count} related workers have been sent the task request"
            )
            print(f"{top_five_workers}")
            messages.success(self.request, "Task created successfully!")
        else:
            print("No related workers found for the task request")
            messages.success(
                self.request, "No related workers found for the task request"
            )

        return super().form_valid(form)


def is_worker(user):
    return user.is_authenticated and user.is_worker


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    """
    Allows updating the status of a `Task` instance. The `Task` model represents a task that can be created by a customer and accepted by a worker.

    Attributes:
        model (Task): The `Task` model to use for the view.
        form_class (TaskStatusUpdateForm): The form to use to update the task status.
        template_name (str): The name of the template to use for rendering the view.
        success_url (str): The URL to redirect to after a successful update.

    Methods:
        form_valid(form): Processes the form after validation, assigns the task to a worker, and creates a notification message. If the task status is "in-progress", it assigns the task to the current user (worker), sets the start time, end time, and total cost of the task, updates other tasks with the same `request_id` to "vanished", and creates a notification message. If the status is "completed" or "rejected", it updates the task status and creates a notification message.
        get_form(form_class=None): Returns an instance of the form to be used in this view. If called from a requested status, it shows only in-progress and rejected options. If called from an in-progress status, it shows only the completed option.
        get_context_data(**kwargs): Adds a boolean value to the context that indicates whether to show the update status field on the template.
    """

    model = Task
    form_class = TaskStatusUpdateForm
    template_name = "tasks/task_update.html"
    success_url = reverse_lazy("tasks:task_list")

    def form_valid(self, form):
        task = form.save(commit=False)
        if task.status == "in-progress":
            # Assign task to worker
            worker = self.request.user.worker
            task.worker = worker
            task.hourly_rate = worker.hourly_rate
            task.start_time = task.start_time.replace(tzinfo=None)
            task.end_time = task.end_time.replace(tzinfo=None)
            task.total_cost = (
                Decimal((task.end_time - task.start_time).total_seconds() / 3600)
                * task.hourly_rate
            )
            task.save()

            # Update other tasks with same request_id to "vanished"
            Task.objects.filter(request_id=task.request_id).exclude(id=task.id).update(
                status="vanished"
            )

            # Create notification message
            TaskNotification.objects.create(
                task=task,
                message=f"Worker - {task.worker.user.username} has accepted the task:'{task.title}'",
                created_time=timezone.now(),
                customer=task.customer,
            )
        else:
            task.save()
            # Create notification message
            message = None
            if task.status == "completed":
                messages.success(
                    self.request, _("Task status set to completed successfully.")
                )
                message = f"Worker - {task.worker.user.username} has completed the task:'{task.title}'"
            elif task.status == "rejected":
                messages.success(
                    self.request, _("Task status set to rejected successfully.")
                )
                message = f"Worker - {task.worker.user.username} has rejected the task:'{task.title}'"
            if message:
                TaskNotification.objects.create(
                    task=task,
                    message=message,
                    created_time=timezone.now(),
                    customer=task.customer,
                )

        return super().form_valid(form)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        task = self.get_object()
        if self.request.GET.get("from_requested") == "true":
            # If called from requested status, show only in-progress and rejected options
            form.fields["status"].choices = [
                ("in-progress", "In Progress"),
                ("rejected", "Rejected"),
            ]
        elif task.status == "in-progress":
            # If called from in-progress status, show only completed option

users/templates/tasks/task_create.html
{% extends 'users/base.html' %} {% block content %}
<div class="container pt-3">
  <h1 class="text-center">Request Task</h1>
  <div class="container w-50">
    <form method="POST">
      {% csrf_token %}
      <div class="form-group mb-3">
        <label for="{{ form.title.id_for_label }}" class="h5">Title</label>
        {{ form.title }}
      </div>
      <div class="form-group mb-3">
        <label for="{{ form.description.id_for_label }}" class="h5"
          >Description</label
        >
        {{ form.description }}
      </div>
      <div class="form-group mb-3">
        <label for="{{ form.location.id_for_label }}" class="h5"
          >Location</label
        >
        {{ form.location }}
      </div>
      <div class="form-group mb-3">
        <label for="{{ form.start_time.id_for_label }}" class="h5"
          >Start Time</label
        >
        <div
          class="input-group date"
          id="datetimepicker1"
          data-target-input="nearest"
        >
          <input
            type="datetime-local"
            class="form-control datetimepicker-input"
            name="start_time"
          />
        </div>
      </div>
      <div class="form-group mb-3">
        <label for="{{ form.end_time.id_for_label }}" class="h5"
          >End Time</label
        >
        <div class="input-group date" data-target-input="nearest">
          <input
            type="datetime-local"
            class="form-control datetimepicker-input"
            name="end_time"
          />
        </div>
      </div>
      <button type="submit" class="btn btn-primary" class="h5">
        Request Task
      </button>
    </form>
  </div>
</div>
<script>
  $(document).ready(function () {
    const startTime = $("input[name='start_time']");
    const endTime = $("input[name='end_time']");

    function CheckDateTime() {
      const start = new Date(startTime.val());
      const end = new Date(endTime.val());
      const hours = (end - start) / (1000 * 60 * 60);
      const now = new Date();

      if (start < now) {
        alert("Start time should be greater than the current time.");
        startTime.val("");
        return;
      }

      if (end <= start) {
        alert("End time should be greater than the start time.");
        endTime.val("");
        return;
      }
    }
    startTime.on("change", CheckDateTime);
    endTime.on("change", CheckDateTime);
  });
</script>
{% endblock %}

users/templates/tasks/task_detail.html
{% extends 'users/base.html' %} {% block content %}
<div class="container pt-4">
  <h1>Task Details</h1>
  <p><strong>Title:</strong> {{ task.title }}</p>
  <p><strong>Description:</strong> {{ task.description }}</p>
  <p><strong>Customer:</strong> {{ task.customer.user.username }}</p>
  <p>
    <strong>Worker:</strong> {% if task.status == 'requested' %}No worker has
    accepted the task yet{% else %}{{ task.worker.user.username }} {% endif %}
  </p>
  <p><strong>Start Time:</strong> {{ task.start_time }}</p>
  <p><strong>End Time:</strong> {{ task.end_time }}</p>
  <p><strong>Location:</strong> {{ task.location }}</p>
  <p>
    <strong>Hourly Rate:</strong>{% if task.status == 'requested' %} Not
    available{% else %} {{ task.hourly_rate }}{% endif %}
  </p>
  <p>
    <strong>Total Cost:</strong>{% if task.status == 'requested' %} Not
    available{% else %} {{ task.total_cost }}{% endif %}
  </p>
  <p><strong>Created Time:</strong> {{ task.created_time }}</p>
  <p><strong>Last Updated Time:</strong> {{ task.last_updated_time }}</p>
  <p><strong>Status:</strong> {{ task.status }}</p>

  {% if task.status == 'completed' and user.is_customer and not task.rating %}
  <form method="post" action="{% url 'tasks:task_rate' task.pk %}">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_rating">Rating:</label>
      <select class="form-control" name="rating" id="id_rating" required>
        <option value="">-- Select rating --</option>
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
      </select>
    </div>
    <div class="form-group">
      <label for="id_review">Review:</label>
      <textarea
        class="form-control"
        name="review"
        id="id_review"
        required
      ></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit Rating</button>
  </form>
  {% elif task.status == 'completed' and user.is_customer and task.rating %}
  <p><strong>Rating:</strong> {{ task.rating }}</p>
  <p><strong>Review:</strong> {{ task.review }}</p>
  {% elif task.status == 'completed' and user.is_worker and task.rating %}
  <p><strong>Rating:</strong> {{ task.rating }}</p>
  <p><strong>Review:</strong> {{ task.review }}</p>
  {% endif %} {% if user.is_worker and task.status == 'requested' %}
  <a href="{% url 'tasks:task_update' task.pk %}" class="btn btn-primary"
    >Update Status</a
  >
  {% endif %} {% if user.is_worker and task.status == 'in-progress' %}
  <a href="{% url 'tasks:task_update' task.pk %}" class="btn btn-primary"
    >Update Status</a
  >
  {% endif %} {% endblock %}
</div>

users/templates/tasks/task_list.html
{% extends 'users/base.html' %} {% block content %} {% if user.is_customer %}
<div class="container pt-4">
  <h1 class="text-center pb-4 text-dark">Task List</h1>
  <div class="row">
    <div class="col-md-3">
      <h4 class="pb-3">Requested Tasks</h4>
      {% if requested_tasks %}
      <div class="list-group">
        {% for task in requested_tasks %}
        <a
          href="{% url 'tasks:task_detail' task.pk %}"
          class="list-group-item list-group-item-action alert alert-danger"
        >
          {{ task.title }}
        </a>
        {% endfor %}
      </div>
      {% else %}
      <p>No requested tasks found.</p>
      {% endif %}
    </div>

    <div class="col-md-3">
      <h4 class="pb-3">In Progress Tasks</h4>
      {% if in_progress_tasks %}
      <div class="list-group">
        {% for task in in_progress_tasks %}

        <a
          href="{% url 'tasks:task_detail' task.pk %}"
          class="list-group-item list-group-item-action alert alert-danger"
        >
          {{ task.title }}
        </a>

        {% endfor %}
      </div>
      {% else %}
      <p>No tasks in progress.</p>
      {% endif %}
    </div>

    <div class="col-md-3">
      <h4 class="pb-3">Completed Tasks</h4>
      {% if completed_tasks %}
      <div class="list-group">
        <h5>Yet to be Rated</h5>
        {% for task in completed_tasks %} {% if task.rating is None %}
        <a
          href="{% url 'tasks:task_detail' task.pk %}"
          class="list-group-item list-group-item-action alert alert-danger"
          >{{ task.title }}</a
        >
        {% endif %} {% endfor %}
        <h5>Already Rated</h5>
        {% for task in completed_tasks %} {% if task.rating %}
        <a
          href="{% url 'tasks:task_detail' task.pk %}"
          class="list-group-item list-group-item-action alert alert-success"
          >{{ task.title }}</a
        >
        {% endif %} {% endfor %}
      </div>
      {% else %}
      <p>No completed tasks found.</p>
      {% endif %}
    </div>

    <div class="col-md-3">
      <h4 class="pb-3">Rejected Tasks</h4>
      {% if rejected_tasks %}
      <div class="list-group">
        {% for task in rejected_tasks %}

        <a
          href="{% url 'tasks:task_detail' task.pk %}"
          class="list-group-item list-group-item-action alert alert-danger"
        >
          {{ task.title }}
        </a>

        {% endfor %}
      </div>
      {% else %}
      <p>No rejected tasks found.</p>
      {% endif %}
    </div>
  </div>
</div>

{% elif user.is_worker %}
<div class="container pt-4">
  <h1 class="text-center pb-3">Task List</h1>

  <div class="row">
    <div class="col-md-3">
      <h4 class="pb-3">Requested Tasks</h4>
      {% if requested_tasks %}
      <div class="list-group">
        {% for task in requested_tasks %}
        <a
          href="{% url 'tasks:task_detail' task.pk %}"
          class="list-group-item list-group-item-action alert alert-danger"
        >
          {{ task.title }}
        </a>
        {% endfor %}
      </div>
      {% else %}
      <p>No requested tasks found.</p>
      {% endif %}
    </div>

    <div class="col-md-3">
      <h4 class="pb-3">In Progress Tasks</h4>
      {% if in_progress_tasks %}
      <div class="list-group">
        {% for task in in_progress_tasks %}
        <a
          href="{% url 'tasks:task_detail' task.pk %}"
          class="list-group-item list-group-item-action alert alert-danger"
        >
          {{ task.title }}
        </a>

        {% endfor %}
      </div>
      {% else %}
      <p>No tasks in progress.</p>
      {% endif %}
    </div>

    <div class="col-md-3">
      <h4 class="pb-3">Completed Tasks</h4>
      {% if completed_tasks %}
      <div class="list-group">
        {% for task in completed_tasks %}

        <a
          href="{% url 'tasks:task_detail' task.pk %}"
          class="list-group-item list-group-item-action alert alert-danger"
        >
          {{ task.title }}
        </a>

        {% endfor %}
      </div>
      {% else %}
      <p>No completed tasks found.</p>
      {% endif %}
    </div>

    <div class="col-md-3">
      <h4 class="pb-3">Rejected Tasks</h4>
      {% if rejected_tasks %}
      <div class="list-group">
        {% for task in rejected_tasks %}

        <a
          href="{% url 'tasks:task_detail' task.pk %}"
          class="list-group-item list-group-item-action alert alert-danger"
        >
          {{ task.title }}
        </a>

        {% endfor %}
      </div>
      {% else %}
      <p>No rejected tasks found.</p>
      {% endif %}
    </div>
  </div>
</div>
{% else %} {% endif %} {% endblock %}

users/templates/tasks/task_update.html
{% extends 'users/base.html' %} {% block content %}
<h1>Update Task Status</h1>
<form method="POST">
  {% csrf_token %} {{ form.as_p }}
  <button class="btn btn-primary" type="submit">Update</button>
</form>
{% endblock %}